name: inkinoRx
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  rxdart: any
  xml: any
  intl: any
  url_launcher: any
  path_provider: any
  shared_preferences: any
  rx_command: 4.0.0
  rx_widgets: any
  get_it: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any

flutter:
  uses-material-design: true
  assets:
  - assets/preloaded_data/theaters.xml
  - assets/images/1x1_transparent.png
  - assets/images/powered_by_tmdb.png